# Generated by Django 6.0 on 2026-01-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_courseoffering_unique_together_and_more'),
        ('doubts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='doubt_type',
            field=models.CharField(choices=[('SECTION', 'Section Doubt'), ('FACULTY', 'Faculty Doubt')], default='SECTION', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doubt',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering'),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
    ]
