# Generated by Django 6.0 on 2026-02-04 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('EVENT', 'Event'), ('WORKSHOP', 'Workshop')], max_length=20)),
                ('organizer', models.CharField(choices=[('CSEA', 'CSEA'), ('CODING_CLUB', 'Coding Club')], max_length=30)),
                ('semester', models.PositiveSmallIntegerField(blank=True, help_text='Applicable semester if not common', null=True)),
                ('is_common', models.BooleanField(default=False, help_text='True if event is for all semesters')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('registration_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
