# Generated by Django 5.2.11 on 2026-03-02 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('club', models.CharField(choices=[('CSEA', 'CSEA'), ('Coding Club', 'Coding Club')], max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Registration Open'), ('closed', 'Registration Closed'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='event_certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='events.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='events.eventregistration')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event'], name='events_even_event_i_9a7faf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['student'], name='events_even_student_eaf200_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'student')},
        ),
    ]
