# Generated by Django 6.0 on 2026-02-04 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='semester',
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Applicable academic year (1–4) if not common', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
