# Generated by Django 5.2.11 on 2026-03-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(max_length=2)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='academics.courseoffering')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_published', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course_offering')},
            },
        ),
        migrations.CreateModel(
            name='MarksSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minor2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_submissions', to='academics.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_entered_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course_offering')},
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_results_published', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
