# Generated by Django 6.0 on 2026-01-14 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_courseoffering_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Ex', 'Excellent'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('P', 'Pass'), ('M', 'Makeup'), ('F', 'Fail'), ('X', 'Absent')], max_length=2)),
                ('grade_point', models.FloatField(editable=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'offering')},
            },
        ),
    ]
