# Generated by Django 5.2.11 on 2026-03-05 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='markssubmission',
            index=models.Index(fields=['course_offering'], name='grades_mark_course__ae1f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='markssubmission',
            index=models.Index(fields=['student'], name='grades_mark_student_160e77_idx'),
        ),
    ]
