# Generated by Django 6.0 on 2026-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_finalgrade_gradeapproval_gradeauditlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markssubmission',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='markssubmission',
            name='end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markssubmission',
            name='mid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markssubmission',
            name='minor1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markssubmission',
            name='minor2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
