# Generated by Django 5.2.11 on 2026-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_markssubmission_grades_mark_course__ae1f0f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
