# Generated by Django 5.2.11 on 2026-03-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        ('grades', '0003_finalgrade_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalgrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='is_backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='finalgrade',
            unique_together={('student', 'course', 'attempt_number')},
        ),
    ]
