# Generated by Django 6.0 on 2026-01-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_courseoffering_unique_together_and_more'),
        ('grades', '0003_remove_markssubmission_total_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksEntryWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('minor1', 'Minor 1'), ('minor2', 'Minor 2'), ('mid', 'Mid'), ('end', 'End')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_windows', to='academics.courseoffering')),
            ],
            options={
                'unique_together': {('course_offering', 'phase')},
            },
        ),
    ]
