# Generated by Django 6.0 on 2026-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
