# Generated by Django 5.2.11 on 2026-03-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_facultyprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin'), ('EXAM_SECTION', 'Exam Section')], max_length=20),
        ),
    ]
