# Generated by Django 5.2.11 on 2026-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(default='OTP', max_length=20),
            preserve_default=False,
        ),
    ]
