# Generated by Django 6.0 on 2026-01-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_courseoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examtype')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('offering', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_text', models.TextField(blank=True)),
                ('syllabus_file', models.FileField(blank=True, null=True, upload_to='exam_syllabus/')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='exams.exam')),
            ],
        ),
    ]
