# Generated by Django 5.2.11 on 2026-02-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        ('accounts', '0002_facultyprofile_is_hod'),
        ('assignments', '0003_alter_assignment_id_alter_assignmentsubmission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.AddField(
            model_name='assignment',
            name='offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='accounts.studentprofile'),
        ),
    ]
