# Generated by Django 5.2.11 on 2026-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignmentsubmission_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
